### PR TITLE
Enable config server for local and Azure Spring Apps

### PR DESCRIPTION
**Pull request by moarychan**
Fixes https://github.com/Azure/reddog-solutions/issues/32
Changelogs:
- Update yaml files for local config server
- Store the dev and prod yaml files in the root folder `config-server`
  
  image

### CODE REVIEW

**Review by thegovind — APPROVED** [review]
👍

**Review by thegovind — CHANGES_REQUESTED** [review]
Looks good @moarychan . Do you mind resolving conflicts due to the other PR that was merged into main? Thanks!

**Comment by moarychan** [comment]
> Looks good @moarychan . Do you mind resolving conflicts due to the other PR that was merged into main? Thanks!

Resolved, please help check!

**Review by thegovind — APPROVED** [review]
LGTM

**Pull request merged**
